### ISSUE TITLE
How to run

### ISSUE THREAD

**Issue by mfnalex** [trigger-segfault/OpenLRR#28]
Hi, maybe I'm stupid but there's absolutely no documentation on how to actually run this. Can someone help me please? Simply cloning the repo into the LRR folder doesn't work, the .exe says it's missing openllr.dll (or openllr-d.dll)

**Comment by trigger-segfault** [comment]
I can try to explain, But I absolutely need to write these instructions down somewhere, and have been putting it off for too long. (Sorry fo the late response).

First, this project will need to be built to run, second you'll need Visual Studio 2019.

## Requirements
The following all need to be moved to `<project>/bin`.

### From this project
* `OpenLRR.exe` (for running release builds)
* `OpenLRR-d.exe` (for running debug builds)

### From a working LRR install
* `Data/` folder
* `LegoRR0.WAD`
* `LegoRR1.WAD`

### From compatibility
* `dgvoodooCpl.exe`
* `dgvoodoo.conf`
* `D3DRM.dll`
* ...

*I'll finish this list once to I get to my computer...*


## Building
1. Open up `OpenLRR.sln` in VS 2019.
2. Change the configuration to **x86**, and **Debug** or **Release**.
3. Build the project **openlrr**, which should automatically output `openlrr.dll` (or `openlrr-d.dll` for **Debug**) to the `bin` folder.

## Running

### Preparing the executable
1. Right click Properties on `OpenLRR.exe` in the bin folder.
2. Goto Compatability.
3. Change the display color depth to **16-bit**.
4. Repeat these steps for `OpenLRR-d.exe`.

### Running in VS debugger
TODO...

**Comment by mfnalex** [comment]
Thanks very much, I'll try it out and close this issue when I got it to work :)

**Comment by mfnalex** [comment]
Awesome, I got it to run, thank you :)
